import { EditorThemeClasses } from "lexical";

export const theme: EditorThemeClasses = {
  root: "wtly__root",
  blockCursor: "wtly__blockCursor",
  characterLimit: "wtly__characterLimit",
  code: `wtly__code`,
  codeHighlight: {
    atrule: "wtly__atrule",
    "attr-name": "wtly__attrName",
    "attr-value": "wtly__attrValue",
    boolean: "wtly__boolean",
    builtin: "wtly__builtin",
    cdata: "wtly__cdata",
    char: "wtly__char",
    class: "wtly__class",
    "class-name": "wtly__className",
    comment: "wtly__comment",
    constant: "wtly__constant",
    deleted: "wtly__deleted",
    doctype: "wtly__doctype",
    entity: "wtly__entity",
    function: "wtly__function",
    important: "wtly__important",
    inserted: "wtly__inserted",
    keyword: "wtly__keyword",
    namespace: "wtly__namespace",
    number: "wtly__number",
    operator: "wtly__operator",
    prolog: "wtly__prolog",
    property: "wtly__property",
    punctuation: "wtly__punctuation",
    regex: "wtly__regex",
    selector: "wtly__selector",
    string: "wtly__string",
    symbol: "wtly__symbol",
    tag: "wtly__tag",
    url: "wtly__url",
    variable: "wtly__variable",
  },
  embedBlock: {
    base: "wtly__embedBlock",
    focus: "wtly__embedBlockFocus",
  },
  hashtag: "wtly__hashtag",
  heading: {
    h1: "wtly__h1",
    h2: "wtly__h2",
    h3: "wtly__h3",
    h4: "wtly__h4",
    h5: "wtly__h5",
    h6: "wtly__h6",
  },

  image: "wtly__image",
  indent: "wtly__indent",
  inlineImage: "wtly__inlineImage",
  layoutContainer: "wtly__layoutContainer",
  layoutItem: "wtly__layoutItem",
  link: "wtly__link",
  list: {
    listitem: "wtly__listItem",
    listitemChecked: "wtly__listItemChecked",
    listitemUnchecked: "wtly__listItemUnchecked",
    nested: {
      list: "wtly__nestedList",
      listitem: "wtly__nestedListItem",
    },
    ol: "wtly__ol",
    ul: "wtly__ul",
    olDepth: ["wtly__ol1", "wtly__ol2", "wtly__ol3", "wtly__ol4", "wtly__ol5"],
    ulDepth: ["wtly__ul1", "wtly__ul2", "wtly__ul3", "wtly__ul4", "wtly__ul5"],
  },
  ltr: "wtly__ltr",
  mark: "wtly__mark",
  markOverlap: "wtly__markOverlap",
  paragraph: "wtly__paragraph",
  quote: "wtly__quote",
  rtl: "wtly__rtl",
  table: "wtly__table",
  tableRow: "wtly__tableRow",
  tableAddColumns: "wtly__tableAddColumns",
  tableAddRows: "wtly__tableAddRows",
  tableCell: "wtly__tableCell",
  tableCellActionButton: "wtly__tableCellActionButton",
  tableCellActionButtonContainer: "wtly__tableCellActionButtonContainer",
  tableCellEditing: "wtly__tableCellEditing",
  tableCellHeader: "wtly__tableCellHeader",
  tableCellPrimarySelected: "wtly__tableCellPrimarySelected",
  tableCellResizer: "wtly__tableCellResizer",
  tableCellSelected: "wtly__tableCellSelected",
  tableCellSortedIndicator: "wtly__tableCellSortedIndicator",
  tableResizeRuler: "wtly__tableCellResizeRuler",
  tableSelected: "wtly__tableSelected",
  tableSelection: "wtly__tableSelection",
  text: {
    base: "wtly__textBase",
    bold: "wtly__textBold",
    code: "wtly__textCode",
    highlight: "wtly__textHighlight",
    italic: "wtly__textItalic",
    strikethrough: "wtly__textStrikethrough",
    subscript: "wtly__textSubscript",
    superscript: "wtly__textSuperscript",
    underline: "wtly__textUnderline",
    underlineStrikethrough: "wtly__textUnderlineStrikethrough",
  },
};
